### ISSUE TITLE
Update command

### ISSUE THREAD

**Issue by benlstumpf** [c3tk/c3tk#12]
Instead of needing to uninstall and reinstall c3tk, be able to run something like "c3tk update" or "c3tk upgrade"

**Comment by ess** [comment]
Perhaps we should consider breaking things up a bit, both the repo and the script.

## The Script ##

If we were to reduce `bin/c3tk` itself down to just the barest of bones necessary to install itself, extracting everything else out to one or more libraries, something like `c3tk install` and `c3tk upgrade` could be as simple as just downloading the newest versions of said libraries.

## The Repo ##

If we were to do the above, we might first want to consider moving this thing to its own GH org so we have a single known good location from which to grab those things.

**Comment by wayneeseguin** [comment]
Thanks for the great suggestion @benlstumpf.
@ess Good thoughts, let's discuss the plan via Slack.
