### ISSUE TITLE
RUNTIME Support

### ISSUE THREAD

**Issue by wayneeseguin** [c3tk/c3tk#27]
Recent changes in Docker Desktop have unfortunately restricted our users from "anyone anywhere" to "personal, small companies". In order to mitigate this we will begin supporting other container runtimes than `docker`.

The first we will support is `podman`, followed by `nerdctl` (via `lima` on osx).

The main challenge at the moment is figuring out how to achieve the volume mounting for command config files and directories to be r/w without introducing onerous work on end users.

Backending these container runtimes for virtualization drivers we explored `multipass`, `qemu`/`lima`, `virtualbox`

For volume mounting we need to explore `smb`, `sshfs`, `virtfs/9p`.

**Comment by wayneeseguin** [comment]
A good comparison of podman vs nerdctl https://codeengineered.com/blog/2021/podman-vs-nerdctl/

**Comment by wayneeseguin** [comment]
It appears that nerdctl is actually kinda epic https://medium.com/nttlabs/nerdctl-359311b32d0e

**Comment by fearoffish** [comment]
For podman to work, we literally swap out the `RUNTIME` like you've already done, but then all images need to be long-names i.e. they *must* include `docker.io/` in their image name. Once we add that, podman 'just works'.

**Comment by fearoffish** [comment]
To clarify, on my Apple M1 I installed podman like so:

```
brew install simnalamburt/x/podman-apple-silicon
podman machine init --cpus=2 --disk-size=20 --memory 4096
podman machine start
podman machine ssh
sudo -i
rpm-ostree install qemu-user-static
systemctl reboot
```

credits to https://edofic.com/posts/2021-09-12-podman-m1-amd64/
This tap includes patches for the M1

**Comment by fearoffish** [comment]
Scratch that...volumes were an issue once I'd shut down docker. :-/

**Comment by fearoffish** [comment]
clearly you know this @wayneeseguin as I see your comment: https://github.com/containers/podman/issues/8016#issuecomment-976013114

:)

**Comment by wayneeseguin** [comment]
Good forward progress, latest here https://gist.github.com/wayneeseguin/7597940a1bb0017e4f86ceabd8bdddc4

Current challenge is networking, when connected to remote systems via VPN everything "just works" via docker but with lima/podman/nerdctl the networking doesn't route as expected.

**Comment by ess** [comment]
@wayneeseguin mentioned this in private, but I wonder what networking model is being used for the podman machine. Like, is it being set up for bridged networking or otherwise?

Seems to me that whatever one it is, you might try forcing it to use the other :D

**Comment by wayneeseguin** [comment]
Current 🐰 🕳️  => https://github.com/lima-vm/lima/blob/master/docs/network.md

**Comment by wayneeseguin** [comment]
With https://github.com/lima-vm/lima/blob/master/examples/vmnet.yaml

**Comment by wayneeseguin** [comment]
For all intents and purposes this feature of c3tk itself works using `RUNTIME=` env var to specify which one should be used and detecting otherwise. I'm closing this issue as networking of other runtimes is a configuration issue of the virtual machine emulation layers not an issue with `c3tk` itself.
