### ISSUE TITLE
Provide a mechanism for fetching all supported tools

### ISSUE THREAD

**Issue by ess** [c3tk/c3tk#8]
The recommended way to install at this point is to grab the script from GH and use its `install` command to install the script. That being the case, you get `c3tk`, but literally nothing else.

As we now have at least a basic `fetch` implementation, we should consider providing a mechanism for using that fetch implementation to grab all of the supported tools that were originally distributed with c3tk.

**Comment by ess** [comment]
This should very much wait until #9 is sorted out, as it were. Otherwise, we're going to land in the same permissions weridness.

**Comment by wayneeseguin** [comment]
This has been completed with the latest PR
