### ISSUE TITLE
Work out the permissions conundrum

### ISSUE THREAD

**Issue by ess** [c3tk/c3tk#9]
At present, we install `c3tk` system-wide via sudo. That's fine and well. However ...

This means that all operations that add/remove commands also require the use of sudo. That's also fine and well. However ...

This means that some or all of the user's own ~/.config/c3tk is scoped to the root user. That's not exactly awesome.

Some thoughts:

Perhaps we should install `c3tk` itself system-wide in a standard location (`/usr/local/bin`), but install commands in the user's context (`~/.config/c3tk/bin`).

This muddies up the waters a bit with the notion of system-wide tools, but not to what I'd think is an untenable degree (we're focusing mostly on the single-user workstation use case, but even so, on a multi-user system, a docker image pulled by one is available to all, so it's really just a matter of creating a symlink in a subsequent user's `.config/c3tk/bin`). We could support multiple paths to get around that as well.

**Comment by wayneeseguin** [comment]
I like the idea of `~/.config/c3tk/bin/ ` as it will be a) isolated and b) consistent with cmds/ and config/

**Comment by ess** [comment]
Throwing together a PR :)

**Comment by ess** [comment]
This was addressed by #10
